// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puqvatperkrpcqmtcpji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cXZhdHBlcmtycGNxbXRjcGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMwOTY2NzMsImV4cCI6MjA5ODY3MjY3M30.hs2KOnCNQ266fl-i-NQvdfmdWtH9YjHr5zMkX1xNALI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});